### ISSUE TITLE
bonfida

### ISSUE THREAD

**Issue by luckynanahe** [WEB3-ALLIANCE/Web3Hackathon2022#20]
Team Name
bonfida

Product Introduction
The mission of the Solana name service is to provide a decentralized and affordable way to map domain names (.sol) to on-chain data. This on-chain data could be anything from a SOL address to IPFS CID, images, text, and what have you.
One of the clear benefits of the name service is to have a human readable name that can map to a SOL address. Why does it matter? Because SOL address formats are a barrier to adoption, and having a human readable address facilitates payments by allowing people to exchange assets by simply sharing a name (e.g bonfida.sol).
Github Link
https://github.com/bmresearch/Bonfidanet

Website
https://naming.bonfida.org/#/

Presentation Materials
https://docs.google.com/presentation/d/1tKBfspBa9_jDb9zwETp8tLDYT6IK1YEK/edit?usp=sharing&ouid=104738321608674891840&rtpof=true&sd=true

Ethereum Wallet Address
0xF1552AFb3A0Dae532BDe0EeB9f240b03c64A90F5

Team Information

Seven, CEO ，working in many departments of Alibaba for ten years, not only has many years of practical experience in the Internet and blockchain industries, but also holds in-depth insights into e-commerce, finance and new media industries. Besides, with the deep involvement of blockchain electronic signature tsign and entrepreneurship of innovative technology media equal ocean, the founder has achieved rapid development in his projects. More importantly, a keen business sense, many entrepreneurial experiences from zero to one, the ability to quickly insight into the essence of business and the systematic management experience enable him to quickly build a combat team. (Telegram handle : @sevenLee)

Timi, co-founder ,engaged in the Internet security industry for many years, has 3 years of experience in the blockchain industry, and has deeply participated in more than 30 GameFi games. (Telegram handle : @crypto20c)

Dary, Chief Promoter & European Regional Marketing Director

Kai, solidity developer, smart contracts

Junsa, front-end developer

Yona, graphic designer

Andy, UI/UE designer

Others
https://twitter.com/GameWayFun
https://t.me/GameWayFun
https://discord.com/invite/R2zA9J75sx
https://www.youtube.com/channel/UCiL-WyjKaAax1cYsTYgZ0uw
https://medium.com/@gameway.fun
https://www.linkedin.com/company/gameway-fun
https://www.facebook.com/GameWayFun2021
https://www.instagram.com/gamewayfun/

**Comment by WEB3-ALLIANCE** [comment]
Please check your team information and edit your own team info.

**Comment by WEB3-ALLIANCE** [comment]
Scam
