### ISSUE TITLE
Web3Hackathon 2022 participation

### ISSUE THREAD

**Issue by periority** [WEB3-ALLIANCE/Web3Hackathon2022#6]
Team Name rzed

 idea and design in detail : finding bugs , we want to do that on web3 project

https://github.com/periority

Ethereum Wallet Address : 0x9815F476ED6Abc217E85464862EAC7214CfED36a

rzed team :  team leader Discord : Reza#2206  Telegram : @rezza   ,  Basic  solidity

**Comment by WEB3-ALLIANCE** [comment]
The issues section is only for registrants product submission.
Please close it if you do not intent to submit any product.
