### ISSUE TITLE
Sol Club#dong#6295

### ISSUE THREAD

**Issue by donggua1024** [WEB3-ALLIANCE/Web3Hackathon2022#8]
- Team Name
SOLCLUB
- Product Introduction
The world and its trading trends are changing very swiftly. The money has been replaced by Bitcoin and we are hearing many explosions like Crypto, NFTs, Forex Trading, and whatnot. The hype started when we started reading the explosion of blockchain news like “Nyan Cat being sold as one,”  “Grimes getting millions of dollars for NFTs” or “That brand sold their ﬁrst NFT for millions”. Before most of the people could jump in, we heard “the founder of Twitter put an autographed tweetup for sale as an NFT”. Now, after months, we are still reading such news and the only difference is, it’s getting hyped with every passing day. 
Though the word NFT lured many, there wasn’t much information available for beginners. People wanted to jump in but they didn’t know where to begin with, how to interact, and how to be persistent in this future-oriented trading ﬁeld. That was the point where we thought of creating a community for all the NFT enthusiasts where they can communicate and collaborate to grow more. That’s how the concept of SolClub began. 
For us, NFTs are not some serious functionless JPEGs, instead, they are fun, usable, and interesting. Also, we wanted to make this an interactive place to be in so the members can get involved in plenty of stuff for a daily booster dose of enjoyment. The ultimate goal is to motivate the entire community to start building projects that can offer way more than some boring JPEGs.
By entering the SolClub Metaverse, you can explore the real potential of NFTs and can be a part of a huge community. That community will help you to grow in the metaverse, explore and learn more, and earn as much as you can. Here, you can literally ‘live’ inside a futuristic digital universe packed with unlimited opportunities. 
- Github Link
 For perfection
- Demo Link
https://twitter.com/SolclubNft/status/1490071373275930627?s=20&t=Q9vNpvsH842TrZpANQZVmA
- Documentation
- https://docs.google.com/document/d/1m8av4DB3iwXEIrmEihCwV7iUAQ-teG5gJsnGE-RCVpQ/edit
-Website
[solclub.io](https://t.co/XC1qvVvKYZ)
- Presentation Materials
- https://drive.google.com/file/d/1KJSF9RB5N-fNE1yRCgX8uJaArfDUmRRT/view
-Ethereum Wallet Address
0xEa62985CeF8823d9dD121aCb7D6fb023C8888888

- Team Information
Astire： Team leader Product Manager / 2D &amp; 3D Designer
Simon Zoller：Front end developer
Simon Cox：product manager
Simon MacCorkindale：designer
- Others
- @SolclubNft This is my twitter homepage We have been in IT field from last 18 years . And we have worked in kind of all sections of information technology .Along with me is some of the best developers in Unreal engine, blockchain and smart contracts.
- Thank you very much for participating in this event in such a simple way

**Comment by WEB3-ALLIANCE** [comment]
scammer
